### ISSUE TITLE
[Bug]: Villager Class Assigning Log Errors

### ISSUE THREAD

**Issue by Vatruvius** [cech12/BrickFurnace#15]
### Minecraft Version

1.18.2

### Forge Version

40.1.74

### Mod Version

1.18.2-1.7.0.0

### Modpack or other Mod

Custom modpack, in development.

### Describe the Issue

Luckily not a startup crash, but there are two errors inside the startup crash log I have. Appears to have to deal with assigning villager class for the Armorer and Butcher. See log specifics below.

### Logs

[https://pastebin.com/rzvwhsve](https://pastebin.com/rzvwhsve)

### Do you use any performance-enhancing mods (e.g. OptiFine)?

OptiFine 1.18.2 HD U H7

**Comment by cech12** [comment]
Thanks for your report! When I have time, I will look into it. :)

**Comment by cech12** [comment]
The error is fixed in the upcoming version 1.18.2-1.7.0.1.
