### ISSUE TITLE
[1.15.2] JEI Integration

### ISSUE THREAD

**Issue by TheUntamed** [cech12/BrickFurnace#2]
Brick Furnace, Brick Blast Furnace, Brick Smoker are all missing in JEI
![Screenshot_47](https://user-images.githubusercontent.com/48363903/79637561-d8b8ad00-8180-11ea-9b45-d5c21106400c.jpg)

**Comment by cech12** [comment]
You are right! I will look at it. :)

**Comment by cech12** [comment]
Done and released in version 1.3.0

**Comment by Tenchu98** [comment]
This issue is back in 1.19.2
latest version of the mod

**Comment by cech12** [comment]
@Tenchu98 The Brick Furnace, Brick Smoker, Brick Blast Furnace should have their own category instead of listed as the vanilla one, because you can add recipes only to the brick variants.

**Comment by Tenchu98** [comment]
Unfortunately the only way to see the recipes that are valid for them is to click the arrow in the gui, which just shows the vanilla block recipes. Hovering and pressing 'u' just shows crafting recipes that use the brick blocks themselves, but not their smelting/blasting/smoking recipes

**Comment by cech12** [comment]
Please open a new issue for that, because this affects another version.
