### ISSUE TITLE
[Bug]: no smelting, blasting, or smoking recipes show in jei.

### ISSUE THREAD

**Issue by Tenchu98** [cech12/BrickFurnace#20]
### Minecraft Version

1.19.2

### Forge Version

43.2.2

### Mod Version

1.8.3

### Modpack or other Mod

Crafttweaker
Custom pack with minimum mods right now

### Describe the Issue

After adding custom recipes through crafttweaker they don't show up in jei. Pressing 'u' while over one of the blocks just shows recipes the blocks can be used to craft.

### Do you use any performance-enhancing mods (e.g. OptiFine)?

Rubidium

**Comment by Tenchu98** [comment]
I should add that the recipes work if I attempt to do them in the blocks, but don't show in jei

**Comment by cech12** [comment]
Thanks for opening the issue. :) 
Could you add your CraftTweaker recipe here that I can test it :)

**Comment by Tenchu98** [comment]
I can grab it when I get home, but its just the example smelting recipes changing the input item to tag: "forge:ores/iron" and the output to <item:minecraft:iron_nugget>

The recipes accepts any iron ore and produces the nugget, but won't show for jei

**Comment by Tenchu98** [comment]
Even if I just enable vanilla recipes they don't show the brick furnace for them in jei

**Comment by cech12** [comment]
That would be great. :)

Which JEI version are you using?

**Comment by Tenchu98** [comment]
Should be jei-1.19.2-forge-11.5.0.297

**Comment by Tenchu98** [comment]
These are my recipes

<recipetype:brickfurnace:smelting>.addJsonRecipe("bricksmelt", {
  ingredient:{item:<item:minecraft:clay_ball>.registryName},
  result:<item:minecraft:brick>.registryName,
  experience:0.3 as float,
  cookingtime:200
});


//Iron
<recipetype:brickfurnace:smelting>.addJsonRecipe("iron_ores", {
  ingredient:{tag:"forge:ores/iron"},
  result:<item:minecraft:iron_nugget>.registryName,
  experience:0.1 as float,
  cookingtime:200
});

<recipetype:brickfurnace:blasting>.addJsonRecipe("blastiron_ores", {
  ingredient:{tag:"forge:ores/iron"},
  result:<item:minecraft:iron_nugget>.registryName,
  experience:0.3 as float,
  cookingtime:200
});
<recipetype:brickfurnace:smelting>.addJsonRecipe("iron_raw", {
  ingredient:{tag:"forge:raw_materials/iron"},
  result:<item:minecraft:iron_nugget>.registryName,
  experience:0.1 as float,
  cookingtime:200
});

<recipetype:brickfurnace:blasting>.addJsonRecipe("blastiron_raw", {
  ingredient:{tag:"forge:raw_materials/iron"},
  result:<item:minecraft:iron_nugget>.registryName,
  experience:0.3 as float,
  cookingtime:200
});


//Copper
<recipetype:brickfurnace:smelting>.addJsonRecipe("copper_ores", {
  ingredient:{tag:"forge:ores/copper"},
  result:<item:create:copper_nugget>.registryName,
  experience:0.1 as float,
  cookingtime:200
});

<recipetype:brickfurnace:blasting>.addJsonRecipe("blastcopper_ores", {
  ingredient:{tag:"forge:ores/copper"},
  result:<item:create:copper_nugget>.registryName,
  experience:0.3 as float,
  cookingtime:200
});

**Comment by cech12** [comment]
Thanks for your report. There was an incompatibility with JEI 11.5.0. I fixed that in the version 1.19.2-1.8.3.1.
