### ISSUE TITLE
What is the name of the config file?

### ISSUE THREAD

**Issue by IlyaTheSawmill** [cech12/BrickFurnace#23]
Just see the title

**Comment by cech12** [comment]
Just see the FAQ:
- https://www.curseforge.com/minecraft/mc-mods/brick-furnace
- https://modrinth.com/mod/brick-furnace

> Where is the config file? 
> There is a defaultconfig directory, where you can find it. If you change something there it has only an effect on new savegames. For existing savegames you need to go to the serverconfig directory of the savegame. 

The name should be clear: "brickfurnace-server.toml"
