### ISSUE TITLE
[Bug]: 2.1.1.0 has a bug with the first item a brick furnace smelts.

### ISSUE THREAD

**Issue by Lcannine** [cech12/BrickFurnace#29]
### Minecraft Version

1.20.1

### Forge Version

47.1.46

### Mod Version

2.1.1.0

### Describe the Issue

2.1.1.0 has a bug where the first item a brick furnace smelts is as fast as a regular furnace, and then the items after are at the configured speed. So, I set brick furnaces to cook twice as slow, but they only cook that slow after the first item is smelted.

### Do you use any performance-enhancing mods (e.g. OptiFine)?

Rubidium

**Comment by cech12** [comment]
Hey, thanks for your report. I will look into that, when I have time :)

**Comment by Lcannine** [comment]
> Hey, thanks for your report. I will look into that, when I have time :)

Of course!

**Comment by cech12** [comment]
Good finding! Fixed in upcoming 1.20.2-2.2.0.1 and 1.20.1-2.1.1.1
