### ISSUE TITLE
[Bug]: Brick Furnace config doesn't let you exclude raw iron and raw gold as things to smelt.

### ISSUE THREAD

**Issue by Lcannine** [cech12/BrickFurnace#30]
### Minecraft Version

1.20.1

### Forge Version

47.1.46

### Mod Version

2.1.1.0

### Describe the Issue

Brick Furnaces cannot be made to exclude iron and gold from their recipes. I'm not sure if this is just the config being wonky or if it's a clash with craft tweaker, but I don't think it's the latter since I'm able to exclude all raw food items from being cooked.

**Comment by cech12** [comment]
Hey, thanks for your report!
Did you add the correct recipes to the blacklist?

minecraft:iron_ingot
minecraft:iron_ingot_from_blasting
minecraft:gold_ingot
minecraft:gold_ingot_from_blasting

If you added some recipes with Crafttweaker, you need to blacklist them, too.

**Comment by Lcannine** [comment]
I'll copy and paste what my blacklist looks like.
recipeBlacklist = "minecraft:iron_ingot,minecraft:gold_ingot,galosphere:silver_ingot,cooked_porkchop,cooked_chicken,baked_potato,cooked_beef,cooked_mutton,cooked_salmon,cooked_cod,cooked_rabbit,dried_kelp,alexsmobs:cooked_lobster_tail,alexsmobs:cooked_catfish,alexsmobs:cooked_moose_ribs,alexsmobs:cooked_kangaroo_meat,alexscaves:cooked_trilocaris_tail,alexscaves:cooked_dinosaur_chop,alexscaves:cooked_radgill,alexscaves:cooked_tripodfish,alexscaves:cooked_lanternfish,alexscaves:cooked_mussel,alexsmobs:boiled_emu_egg,"
I didn't change any smelting recipes with craft tweaker, just crafting table ones. Also, despite not putting "Minecraft:" before the food items, they're blacklisted just fine. The alex's mobs items also are completely blacklisted while the alex's caves ones aren't, but I think the latter is an issue with alex's caves lacking IDs.

**Comment by Lcannine** [comment]
Oh yeah, it can still smelt the galosphere ingot, so maybe its something with non-food items...?

**Comment by cech12** [comment]
And you are testing with a brick furnace, not with a brick blast furnace?

The brick blast furnace recepies must be also blacklisted to be excluded there. 

please see the wiki: https://github.com/cech12/BrickFurnace/wiki#recipeblacklist-since-150

**Comment by cech12** [comment]
For the alexcaves mod, here is a list of all recipes: https://github.com/AlexModGuy/AlexsCaves/tree/main/src%2Fmain%2Fresources%2Fdata%2Falexscaves%2Frecipes

To blacklist one, it should look like this:

alexscaves:furnace/cooked_radgill_furnace

**Comment by Lcannine** [comment]
> And you are testing with a brick furnace, not with a brick blast furnace?
> 
> The brick blast furnace recepies must be also blacklisted to be excluded there.
> 
> please see the wiki: https://github.com/cech12/BrickFurnace/wiki#recipeblacklist-since-150

Yes, only the base brick furnace. Does this mean that I cannot only make it to where the brick blast furnace can smelt iron and gold? It has to be blacklisted for both?

**Comment by Lcannine** [comment]
> For the alexcaves mod, here is a list of all recipes: https://github.com/AlexModGuy/AlexsCaves/tree/main/src%2Fmain%2Fresources%2Fdata%2Falexscaves%2Frecipes
> 
> To blacklist one, it should look like this:
> 
> alexscaves:furnace/cooked_radgill_furnace

thanks

**Comment by cech12** [comment]
Hey, sorry the vanilla recipes changed in 1.20

The correct names for iron are:
iron_ingot_from_blasting_deepslate_iron_ore,iron_ingot_from_blasting_iron_ore.json,iron_ingot_from_blasting_raw_iron,iron_ingot_from_smelting_deepslate_iron_ore,iron_ingot_from_smelting_iron_ore.json,iron_ingot_from_smelting_raw_iron

And for gold:
gold_ingot_from_blasting_deepslate_gold_ore,gold_ingot_from_blasting_gold_ore,gold_ingot_from_blasting_nether_gold_ore,gold_ingot_from_blasting_raw_gold,gold_ingot_from_smelting_deepslate_gold_ore,gold_ingot_from_smelting_gold_ore,gold_ingot_from_smelting_nether_gold_ore,gold_ingot_from_smelting_raw_gold

**Comment by Lcannine** [comment]
> Hey, sorry the vanilla recipes changed in 1.20
> 
> The correct names for iron are: iron_ingot_from_blasting_deepslate_iron_ore,iron_ingot_from_blasting_iron_ore.json,iron_ingot_from_blasting_raw_iron,iron_ingot_from_smelting_deepslate_iron_ore,iron_ingot_from_smelting_iron_ore.json,iron_ingot_from_smelting_raw_iron
> 
> And for gold: gold_ingot_from_blasting_deepslate_gold_ore,gold_ingot_from_blasting_gold_ore,gold_ingot_from_blasting_nether_gold_ore,gold_ingot_from_blasting_raw_gold,gold_ingot_from_smelting_deepslate_gold_ore,gold_ingot_from_smelting_gold_ore,gold_ingot_from_smelting_nether_gold_ore,gold_ingot_from_smelting_raw_gold

Thank you so much!
