### ISSUE TITLE
[Bug]: When quickly inputting and outputting an item from a brick furnace, the modified timer is ignored.

### ISSUE THREAD

**Issue by Lcannine** [cech12/BrickFurnace#31]
### Minecraft Version

1.20.1

### Forge Version

47.1.46

### Mod Version

2.1.1.1

### Describe the Issue

When an item is first put into a brick furnace, then the modified timer is applied. However, if I were to just simply click on it (and thus take it out of the furnace) and put it right back, the modified timer is ignored for one item. This process can naturally be repeated to essentially ignore the modified timer.

### Do you use any performance-enhancing mods (e.g. OptiFine)?

Rubidium

**Comment by Lcannine** [comment]
I think what it is that it only applies the modifier to the first item for the first time the brick furnace is placed, because even when I leave the interface, re-putting the item makes the furnace ignore the timer.

**Comment by cech12** [comment]
Thanks for your report, I will look into that when I have time :)

**Comment by cech12** [comment]
Fixed in the upcoming versions 1.20.1-2.1.1.2 & 1.20.2-2.2.0.2
