### ISSUE TITLE
[Feature]: Please change the setting to allow typing the value instead of a slider for cook time in percentages!

### ISSUE THREAD

**Issue by NattoRiisa** [cech12/BrickFurnace#34]
### Describe the Feature

Makes things less annoying ;;

**Comment by cech12** [comment]
That is the default for numbers. I will look into that when I have time.

**Comment by cech12** [comment]
@NattoRiisa Thanks for your hint. The slider was changed to a text field in the upcoming version 1.21-4.1.1.0.
