### ISSUE TITLE
Brick Furnaces smelt nuggets

### ISSUE THREAD

**Issue by Alpha-72** [cech12/BrickFurnace#6]
Hello,

Would it be possible to add a config option for brick furnaces to smelt ore into nuggets instead of ingots? This would help solidify them as a go-to for terra-cotta and glass rather than ore. 

Thanks,
Alpha

**Comment by cech12** [comment]
Hey! Thanks for your idea! I think, adding or changing specific recipes is not the right way for this mod. But I like the idea. Maybe data pack related recipes are a good alternative to support ideas like yours.

**Comment by cech12** [comment]
Changes were released in 1.5.0
You can disable or blacklist vanilla recipes via the server config and you can add recipes via data packs. (see wiki) :D

I hope, that helps you. :D
